### ISSUE TITLE
Shipping as a Chrome extension or app?

### ISSUE THREAD

**Issue by myst729** [devanlai/webdfu#10]
Since it is entirely written in JavaScript and only supported by Chrome, Chrome extension looks like a perfect production form for this project.

**Comment by devanlai** [comment]
Hi @myst729,

I'm not doing much work on this demo these days, but I think it would make more sense to build the functionality into a Progressive Web Application, rather than making an extension. That would provide the option of installing it to make it accessible offline (both on the desktop and on mobile, which doesn't support extensions) without making installation a requirement.

**Comment by myst729** [comment]
Sounds more reasonable than what I thought.
