### ISSUE TITLE
webusb broken in new chrome

### ISSUE THREAD

**Issue by astwist** [devanlai/webdfu#3]
Hi devanlai,
The latest version of chrome has broken webdfu

When we connect to the device we get error:
InvalidStateError: The device must have a configuration selected.

It works fine with chrome 60.x.x.x.x.x but not with 70.x.x.x.x.x
Any ideas?
Thanks

**Comment by devanlai** [comment]
Hi @alkex1982, thank you for bringing this to my attention.

It looks to me like Chrome 77 introduced some internal WebUSB changes, one of which is that control transfers are disallowed if the device is unconfigured. This causes issues with part of the dfu-util initialization, where I am manually reading the configuration descriptor and string descriptors to work around [chrome bug 727819](https://bugs.chromium.org/p/chromium/issues/detail?id=727819).

It looks like there are a couple of possible workarounds:

1. Change `fixInterfaceNames` to select a configuration before attempting to read any descriptors. I avoided this in the past, because it doesn't really make sense to set a configuration just to read some descriptors. In practice, given that the vast majority of devices only have one configuration, maybe it's no big deal.
2. Skip `fixInterfaceNames` entirely. This would avoid messing with the device configuration before we've decided to claim the device, but would be problematic for DfuSE devices, which can have multiple DFU interfaces that need to be distinguished by name.

@reillyeon, I believe that this new behavior with the `ensureDeviceConfigured` check on control transfers is a bit too strict in the case of `GET_DESCRIPTOR` requests, as those are obviously required by the USB spec regardless of the configuration state.

**Comment by reillyeon** [comment]
Allowing control transfers with a recipient of "device" when the device is unconfigured seems reasonable.

This appears to be the behavior I anticipated in the specification. Can you file an issue on crbug.com to fix the implementation?

**Comment by devanlai** [comment]
Looking back at the spec, the algorithm for validating control transfer parameters does say to [abort if the device is not configured](https://wicg.github.io/webusb/#check-the-validity-of-the-control-transfer-parameters):

> To **check the validity of the control transfer parameters** perform the following steps:
> 1. Let _setup_ be the [USBControlTransferParameters](https://wicg.github.io/webusb/#dom-usbrecipient-interface) created for the transfer.
> 2. Let _promise_ be the promise created for the transfer.
> 3. Let _configuration_ be the [active configuration](https://wicg.github.io/webusb/#active-configuration).  If the device is not configured abort these steps.
> ...

It goes on to describe validation steps for `interface` and `endpoint` recipients, but not `device`.

So it looks like this would need to be amended and defined in the WebUSB spec first.

**Comment by reillyeon** [comment]
It's okay that the control transfer validation steps abort if the device is unconfigured because the algorithm calling it only checks if the Promise is rejected. Otherwise it continues with sending the transfer to the device.
