### ISSUE TITLE
STM32F042 device in DFU mode not recognized on demo website

### ISSUE THREAD

**Issue by ankoornoisee** [devanlai/webdfu#5]
I have an STM32F042 device connected to my computer in DFU mode using the dfuse bootloader (I've verified that it's connected by checking windows device manager). when I enter the device vendor id and click connect, there is a popup "no compatible devices found". Does this library support  connecting to STM32F0 devices in DFU mode?

**Comment by devanlai** [comment]
The library is intended to work with the STM32F0's built-in DfuSE bootloader and to the best of my knowledge, it generally does work with that bootloader.

Testing on my Window 7 desktop with Chrome 78, I didn't encounter any issues using vendor ID 0x0483 (it's also not really necessary to enter the vendor ID unless you have a lot of USB devices connected that you want to filter out).

Can you confirm that the USB DFU interface is using the WinUSB/libUSB driver? It's been a while since installed any of ST's tools, but I don't recall if their DFU utilities use WinUSB and handle it in user space, or if they install a custom USB driver that would prevent Chrome from talking to the bootloade via WebUSB. You can use a tool like [Zadig](https://zadig.akeo.ie/) to replace the driver with the WinUSB driver.

**Comment by ankoornoisee** [comment]
Thanks, I used Zadig to replace the driver with the WinUSB driver and your demo website now recognizes my STM32 device in DFU mode and lets me flash it successfully.
